CREATE DATABASE Exercise3;
USE Exercise3;
CREATE TABLE cars (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
brand VARCHAR(50) NOT NULL,
model VARCHAR(50) NOT NULL,
year INT(4) NOT NULL,
color VARCHAR(50) NOT NULL
);